import {DefaultDataFactory} from "@opennetwork/rdf-data-model";

export const contains = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/contains")
export const is = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/is")
export const type = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type")
export const typeQuad = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/quad")
export const typeQuadLike = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/quad-like")
export const typeUnknown = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/unknown")
export const typeAsyncIterable = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/async-iterable")
export const typeIterable = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/iterable")
export const typeFunction = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/function")
export const typePromise = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/promise")
export const typeString = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/string")
export const typeNumber = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/number")
export const typeBoolean = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/boolean")
export const typeBigint = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/bigint")
export const typeDate = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/date")
export const typeBinary = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/binary")
export const typeHex = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/binary-hex")
export const typeBase64 = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/binary-base64")
export const typeLiteral = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/literal")
export const typeLiteralLike = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/literal-like")
export const typeJSON = DefaultDataFactory.namedNode("https://types.open-network.dev/aware-consumer/type/json")
